spring:
  application:
    name: JTPGateway

  cloud:
    gateway:
      routes:
      - id: joetravelplanner
        uri: lb://joetravelplanner
        predicates:
        - Path=/backendApi/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"

eureka:
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka/ 
    enabled: true
  instance:
    ip-address: localhost 

server:
  port: 9003


      
      
        
      
  
          
